// @ts-check

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const cwd = process.cwd();

const pkgJson = JSON.parse(readFileSync(join(cwd, "package.json"), "utf-8"));
const exports = Object.keys(pkgJson.exports)
  .filter((key) => key.startsWith("./"))
  .map((key) => key.replace("./", ""))
  .filter((key) => !key.includes("."));

console.log("Generating files for exports: ", exports);

for (const name of exports) {
  writeFileSync(
    join(cwd, `${name}.js`),
    `// This file is automatically generated to support backward compatibility with imports
// Do not edit it or commit it to the git. Only used for publishing to NPM.
module.exports = require("./cjs/${name}");
`
  );
  writeFileSync(
    join(cwd, `${name}.d.ts`),
    `// This file is automatically generated to support backward compatibility with imports
// Do not edit it or commit it to the git. Only used for publishing to NPM.
export * from "./cjs/${name}";
`
  );
}

process.exit(0);
