name: Publish
on:
  tags:
    - "*"

env:
  NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

jobs:
  publish-jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Publish package to JSR
        run: npx -y jsr publish

  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"
      - name: Setup NPM TOKEN
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: yarn install
      - name: Publish to NPM
        run: npm publish
